// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectK.Infrastructure.DbContexts;

#nullable disable

namespace ProjectK.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821224219_AddMemberEntity")]
    partial class AddMemberEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.Property<Guid>("GroupKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupKey");

                    b.HasIndex("KurinKey");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Kurin", b =>
                {
                    b.Property<Guid>("KurinKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KurinKey");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Kurins");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Member", b =>
                {
                    b.Property<Guid>("MemberKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberKey");

                    b.HasIndex("GroupKey");

                    b.HasIndex("KurinKey");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("Groups")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurin");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Member", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("Members")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Kurin");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Kurin", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
