// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectK.Infrastructure.DbContexts;

#nullable disable

namespace ProjectK.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527190500_AddGroupSilhouetteField")]
    partial class AddGroupSilhouetteField
    {
    }
}
