// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectK.Infrastructure.DbContexts;

#nullable disable

namespace ProjectK.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectK.Common.Entities.AuthModule.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ProjectK.Common.Entities.AuthModule.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.Property<Guid>("GroupKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupKey");

                    b.HasIndex("KurinKey");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Kurin", b =>
                {
                    b.Property<Guid>("KurinKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KurinKey");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Kurins");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Leadership", b =>
                {
                    b.Property<Guid>("LeadershipKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GroupKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("LeadershipKey");

                    b.HasIndex("GroupKey")
                        .IsUnique()
                        .HasFilter("[GroupKey] IS NOT NULL");

                    b.HasIndex("KurinKey");

                    b.HasIndex("Type", "KurinKey", "GroupKey");

                    b.ToTable("Leaderships");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.LeadershipHistory", b =>
                {
                    b.Property<Guid>("LeadershipHistoryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeadershipKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("LeadershipHistoryKey");

                    b.HasIndex("MemberKey", "StartDate");

                    b.HasIndex("LeadershipKey", "Role", "StartDate");

                    b.ToTable("LeadershipHistories");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Member", b =>
                {
                    b.Property<Guid>("MemberKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatestPlastLevel")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberKey");

                    b.HasIndex("GroupKey");

                    b.HasIndex("KurinKey");

                    b.HasIndex("UserKey")
                        .IsUnique()
                        .HasFilter("[UserKey] IS NOT NULL");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.ParticipantBusyRange", b =>
                {
                    b.Property<Guid>("ParticipantBusyRangeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanningParticipantKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("ParticipantBusyRangeKey");

                    b.HasIndex("PlanningParticipantKey");

                    b.ToTable("ParticipantBusyRanges");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningParticipant", b =>
                {
                    b.Property<Guid>("PlanningParticipantKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanningSessionKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RoleWeight")
                        .HasColumnType("float");

                    b.HasKey("PlanningParticipantKey");

                    b.HasIndex("PlanningSessionKey");

                    b.ToTable("PlanningParticipants");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningSession", b =>
                {
                    b.Property<Guid>("PlanningSessionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ConflictScore")
                        .HasColumnType("float");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OptimalEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OptimalStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SearchEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SearchStart")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanningSessionKey");

                    b.HasIndex("KurinKey");

                    b.ToTable("PlanningSessions");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.PlastLevelHistory", b =>
                {
                    b.Property<Guid>("PlastLevelHistoryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateAchieved")
                        .HasColumnType("date");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlastLevel")
                        .HasColumnType("int");

                    b.HasKey("PlastLevelHistoryKey");

                    b.HasIndex("MemberKey");

                    b.ToTable("PlastLevelHistories");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgress", b =>
                {
                    b.Property<Guid>("BadgeProgressKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedByRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReviewedByUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BadgeProgressKey");

                    b.HasIndex("MemberKey", "BadgeId")
                        .IsUnique();

                    b.ToTable("BadgeProgresses");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgressAuditEvent", b =>
                {
                    b.Property<Guid>("BadgeProgressAuditEventKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ActorUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BadgeProgressKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BadgeProgressAuditEventKey");

                    b.HasIndex("BadgeProgressKey");

                    b.ToTable("BadgeProgressAuditEvents");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbePointProgress", b =>
                {
                    b.Property<Guid>("ProbePointProgressKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProbeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedByRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SignedByUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProbePointProgressKey");

                    b.HasIndex("MemberKey", "ProbeId", "PointId")
                        .IsUnique();

                    b.ToTable("ProbePointProgresses");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgress", b =>
                {
                    b.Property<Guid>("ProbeProgressKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedByRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CompletedByUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KurinKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProbeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiedByRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VerifiedByUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProbeProgressKey");

                    b.HasIndex("MemberKey", "ProbeId")
                        .IsUnique();

                    b.ToTable("ProbeProgresses");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgressAuditEvent", b =>
                {
                    b.Property<Guid>("ProbeProgressAuditEventKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ActorUserKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProbeProgressKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProbeProgressAuditEventKey");

                    b.HasIndex("ProbeProgressKey");

                    b.ToTable("ProbeProgressAuditEvents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("Groups")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurin");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Leadership", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Group", "Group")
                        .WithOne("Leadership")
                        .HasForeignKey("ProjectK.Common.Entities.KurinModule.Leadership", "GroupKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("Leaderships")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("Kurin");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.LeadershipHistory", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Leadership", "Leadership")
                        .WithMany("LeadershipHistories")
                        .HasForeignKey("LeadershipKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectK.Common.Entities.KurinModule.Member", "Member")
                        .WithMany("LeadershipHistories")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leadership");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Member", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("Members")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjectK.Common.Entities.AuthModule.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("ProjectK.Common.Entities.KurinModule.Member", "UserKey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Kurin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.ParticipantBusyRange", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Planning.PlanningParticipant", "PlanningParticipant")
                        .WithMany("BusyRanges")
                        .HasForeignKey("PlanningParticipantKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningParticipant");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningParticipant", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Planning.PlanningSession", "PlanningSession")
                        .WithMany("Participants")
                        .HasForeignKey("PlanningSessionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningSession");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningSession", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Kurin", "Kurin")
                        .WithMany("PlanningSessions")
                        .HasForeignKey("KurinKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurin");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.PlastLevelHistory", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Member", "Member")
                        .WithMany("PlastLevelHistory")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgress", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Member", "Member")
                        .WithMany("BadgeProgresses")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgressAuditEvent", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgress", "BadgeProgress")
                        .WithMany("AuditEvents")
                        .HasForeignKey("BadgeProgressKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeProgress");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbePointProgress", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Member", "Member")
                        .WithMany("ProbePointProgresses")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgress", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.KurinModule.Member", "Member")
                        .WithMany("ProbeProgresses")
                        .HasForeignKey("MemberKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgressAuditEvent", b =>
                {
                    b.HasOne("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgress", "ProbeProgress")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ProbeProgressKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProbeProgress");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Group", b =>
                {
                    b.Navigation("Leadership")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Kurin", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Leaderships");

                    b.Navigation("Members");

                    b.Navigation("PlanningSessions");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Leadership", b =>
                {
                    b.Navigation("LeadershipHistories");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Member", b =>
                {
                    b.Navigation("BadgeProgresses");

                    b.Navigation("LeadershipHistories");

                    b.Navigation("PlastLevelHistory");

                    b.Navigation("ProbePointProgresses");

                    b.Navigation("ProbeProgresses");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningParticipant", b =>
                {
                    b.Navigation("BusyRanges");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.KurinModule.Planning.PlanningSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.BadgeProgress", b =>
                {
                    b.Navigation("AuditEvents");
                });

            modelBuilder.Entity("ProjectK.Common.Entities.ProbesAndBadgesModule.ProbeProgress", b =>
                {
                    b.Navigation("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
