name: Frontend CI/CD to Azure SWA

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'Frontend/**'

jobs:
  lint_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: Frontend/projectk-frontend/package-lock.json

      - run: npm ci
        working-directory: Frontend/projectk-frontend

      - name: Run lint
        run: npm run lint
        working-directory: Frontend/projectk-frontend

      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: Frontend/projectk-frontend

  build_and_deploy:
    needs: lint_and_test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure SWA
    environment:
      name: ${{ github.event_name == 'push' && 'production' || 'staging' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
          
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
        
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
           
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_BEACH_0EA172703 }}
          action: "upload"
          app_location: "./Frontend"
          api_location: ""
          output_location: "dist/projectk-frontend/browser"
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_BEACH_0EA172703 }}
          action: "close"