name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**'
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract Release Info
      if: github.event_name == 'release'
      shell: bash
      run: |
        RAW_TAG="${{ github.event.release.tag_name }}"
        CLEAN_VERSION="${RAW_TAG#v}"
        
        RELEASE_NAME='${{ github.event.release.name }}'
        
        CODE_NAME=$(echo "$RELEASE_NAME" | grep -oP '"\K[^"]+' || echo "$RELEASE_NAME")
        
        echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
        echo "CODENAME=$CODE_NAME" >> $GITHUB_ENV

    - name: Inject Versioning
      if: github.event_name == 'release'
      shell: bash
      run: |
        FILES=$(find Backend/ProjectK.Backend/ProjectK.API/ -name "appsettings*.json")
        echo "Updating files: $FILES"
        
        for file in $FILES; do
          sed -i "s/v0.0.0-dev/${{ env.VERSION }}/g" "$file"
          sed -i "s/LocalDevelopment/${{ env.CODENAME }}/g" "$file"
        done

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore Backend/ProjectK.Backend
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
      
    - name: Build
      run: dotnet build Backend/ProjectK.Backend --configuration Release --no-restore
    
    - name: Test
      run: dotnet test Backend/ProjectK.Backend --configuration Release --no-build --verbosity normal

    - name: Publish Artifact
      run: dotnet publish Backend/ProjectK.Backend/ProjectK.API/ProjectK.API.csproj -c Release -o ./publish
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./publish/

  deploy:
    if: github.event_name == 'release'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'api-projectk-prod'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish