name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore Backend/ProjectK.Backend
      
    - name: Build
      run: dotnet build Backend/ProjectK.Backend --configuration Release --no-restore
    
    - name: Test
      run: dotnet test Backend/ProjectK.Backend --no-build --verbosity normal

    - name: Publish Artifact
      run: dotnet publish Backend/ProjectK.Backend -c Release -o ./publish
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./publish

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'api-projectk-prod'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish